import React from 'react';

export default function CountriesOption() {
  const countries = [
    { id: 'AF-sky', name: 'Afghanistan' },
    { id: 'AL-sky', name: 'Albania' },
    { id: 'DZ-sky', name: 'Algeria' },
    { id: 'AS-sky', name: 'American Samoa' },
    { id: 'AD-sky', name: 'Andorra' },
    { id: 'AO-sky', name: 'Angola' },
    { id: 'AI-sky', name: 'Anguilla' },
    { id: 'AQ-sky', name: 'Antarctica' },
    { id: 'AG-sky', name: 'Antigua and Barbuda' },
    { id: 'AR-sky', name: 'Argentina' },
    { id: 'AM-sky', name: 'Armenia' },
    { id: 'AW-sky', name: 'Aruba' },
    { id: 'AU-sky', name: 'Australia' },
    { id: 'AT-sky', name: 'Austria' },
    { id: 'AZ-sky', name: 'Azerbaijan' },
    { id: 'BS-sky', name: 'Bahamas' },
    { id: 'BH-sky', name: 'Bahrain' },
    { id: 'BD-sky', name: 'Bangladesh' },
    { id: 'BB-sky', name: 'Barbados' },
    { id: 'BY-sky', name: 'Belarus' },
    { id: 'BE-sky', name: 'Belgium' },
    { id: 'BZ-sky', name: 'Belize' },
    { id: 'BJ-sky', name: 'Benin' },
    { id: 'BM-sky', name: 'Bermuda' },
    { id: 'BT-sky', name: 'Bhutan' },
    { id: 'BO-sky', name: 'Bolivia' },
    { id: 'BA-sky', name: 'Bosnia and Herzegovina' },
    { id: 'BW-sky', name: 'Botswana' },
    { id: 'BV-sky', name: 'Bouvet Island' },
    { id: 'BR-sky', name: 'Brazil' },
    { id: 'IO-sky', name: 'British Indian Ocean Territory' },
    { id: 'VG-sky', name: 'British Virgin Islands' },
    { id: 'BN-sky', name: 'Brunei' },
    { id: 'BG-sky', name: 'Bulgaria' },
    { id: 'BF-sky', name: 'Burkina Faso' },
    { id: 'BI-sky', name: 'Burundi' },
    { id: 'KH-sky', name: 'Cambodia' },
    { id: 'CM-sky', name: 'Cameroon' },
    { id: 'CA-sky', name: 'Canada' },
    { id: 'CV-sky', name: 'Cape Verde' },
    { id: 'BQ-sky', name: 'Caribbean Netherlands' },
    { id: 'KY-sky', name: 'Cayman Islands' },
    { id: 'CF-sky', name: 'Central African Republic' },
    { id: 'TD-sky', name: 'Chad' },
    { id: 'CL-sky', name: 'Chile' },
    { id: 'CN-sky', name: 'China' },
    { id: 'CX-sky', name: 'Christmas Island' },
    { id: 'CC-sky', name: 'Cocos (Keeling) Islands' },
    { id: 'CO-sky', name: 'Colombia' },
    { id: 'KM-sky', name: 'Comoros' },
    { id: 'CK-sky', name: 'Cook Islands' },
    { id: 'CR-sky', name: 'Costa Rica' },
    { id: 'CE-sky', name: 'Crimea' },
    { id: 'HR-sky', name: 'Croatia' },
    { id: 'CU-sky', name: 'Cuba' },
    { id: 'CW-sky', name: 'Curacao' },
    { id: 'CY-sky', name: 'Cyprus' },
    { id: 'CZ-sky', name: 'Czechia' },
    { id: 'CD-sky', name: 'DR Congo' },
    { id: 'DK-sky', name: 'Denmark' },
    { id: 'DJ-sky', name: 'Djibouti' },
    { id: 'DM-sky', name: 'Dominica' },
    { id: 'DO-sky', name: 'Dominican Republic' },
    { id: 'EC-sky', name: 'Ecuador' },
    { id: 'EG-sky', name: 'Egypt' },
    { id: 'SV-sky', name: 'El Salvador' },
    { id: 'GQ-sky', name: 'Equatorial Guinea' },
    { id: 'ER-sky', name: 'Eritrea' },
    { id: 'EE-sky', name: 'Estonia' },
    { id: 'SZ-sky', name: 'Eswatini' },
    { id: 'ET-sky', name: 'Ethiopia' },
    { id: 'FK-sky', name: 'Falkland Islands' },
    { id: 'FO-sky', name: 'Faroe Islands' },
    { id: 'FJ-sky', name: 'Fiji' },
    { id: 'FI-sky', name: 'Finland' },
    { id: 'FR-sky', name: 'France' },
    { id: 'GF-sky', name: 'French Guiana' },
    { id: 'PF-sky', name: 'French Polynesia' },
    { id: 'TF-sky', name: 'French Southern Territories' },
    { id: 'GA-sky', name: 'Gabon' },
    { id: 'GM-sky', name: 'Gambia' },
    { id: 'GE-sky', name: 'Georgia' },
    { id: 'DE-sky', name: 'Germany' },
    { id: 'GH-sky', name: 'Ghana' },
    { id: 'GI-sky', name: 'Gibraltar' },
    { id: 'GR-sky', name: 'Greece' },
    { id: 'GL-sky', name: 'Greenland' },
    { id: 'GD-sky', name: 'Grenada' },
    { id: 'GP-sky', name: 'Guadeloupe' },
    { id: 'GU-sky', name: 'Guam' },
    { id: 'GT-sky', name: 'Guatemala' },
    { id: 'GG-sky', name: 'Guernsey' },
    { id: 'GN-sky', name: 'Guinea' },
    { id: 'GW-sky', name: 'Guinea-Bissau' },
    { id: 'GY-sky', name: 'Guyana' },
    { id: 'HT-sky', name: 'Haiti' },
    { id: 'HM-sky', name: 'Heard and McDonald Islands' },
    { id: 'HN-sky', name: 'Honduras' },
    { id: 'HK-sky', name: 'Hong Kong' },
    { id: 'HU-sky', name: 'Hungary' },
    { id: 'IS-sky', name: 'Iceland' },
    { id: 'IN-sky', name: 'India' },
    { id: 'ID-sky', name: 'Indonesia' },
    { id: 'IR-sky', name: 'Iran' },
    { id: 'IQ-sky', name: 'Iraq' },
    { id: 'IE-sky', name: 'Ireland' },
    { id: 'IL-sky', name: 'Israel' },
    { id: 'IT-sky', name: 'Italy' },
    { id: 'CI-sky', name: 'Ivory Coast' },
    { id: 'JM-sky', name: 'Jamaica' },
    { id: 'JP-sky', name: 'Japan' },
    { id: 'JO-sky', name: 'Jordan' },
    { id: 'KZ-sky', name: 'Kazakhstan' },
    { id: 'KE-sky', name: 'Kenya' },
    { id: 'KI-sky', name: 'Kiribati' },
    { id: 'KO-sky', name: 'Kosovo' },
    { id: 'KW-sky', name: 'Kuwait' },
    { id: 'KG-sky', name: 'Kyrgyzstan' },
    { id: 'LA-sky', name: 'Laos' },
    { id: 'LV-sky', name: 'Latvia' },
    { id: 'LB-sky', name: 'Lebanon' },
    { id: 'LS-sky', name: 'Lesotho' },
    { id: 'LR-sky', name: 'Liberia' },
    { id: 'LY-sky', name: 'Libya' },
    { id: 'LI-sky', name: 'Liechtenstein' },
    { id: 'LT-sky', name: 'Lithuania' },
    { id: 'LU-sky', name: 'Luxembourg' },
    { id: 'MO-sky', name: 'Macau' },
    { id: 'MG-sky', name: 'Madagascar' },
    { id: 'MW-sky', name: 'Malawi' },
    { id: 'MY-sky', name: 'Malaysia' },
    { id: 'MV-sky', name: 'Maldives' },
    { id: 'ML-sky', name: 'Mali' },
    { id: 'MT-sky', name: 'Malta' },
    { id: 'MH-sky', name: 'Marshall Islands' },
    { id: 'MQ-sky', name: 'Martinique' },
    { id: 'MR-sky', name: 'Mauritania' },
    { id: 'MU-sky', name: 'Mauritius' },
    { id: 'YT-sky', name: 'Mayotte' },
    { id: 'MX-sky', name: 'Mexico' },
    { id: 'FM-sky', name: 'Micronesia' },
    { id: 'MD-sky', name: 'Moldova' },
    { id: 'MC-sky', name: 'Monaco' },
    { id: 'MN-sky', name: 'Mongolia' },
    { id: 'ME-sky', name: 'Montenegro' },
    { id: 'MS-sky', name: 'Montserrat' },
    { id: 'MA-sky', name: 'Morocco' },
    { id: 'MZ-sky', name: 'Mozambique' },
    { id: 'MM-sky', name: 'Myanmar' },
    { id: 'NA-sky', name: 'Namibia' },
    { id: 'NR-sky', name: 'Nauru' },
    { id: 'NP-sky', name: 'Nepal' },
    { id: 'NL-sky', name: 'Netherlands' },
    { id: 'NC-sky', name: 'New Caledonia' },
    { id: 'NZ-sky', name: 'New Zealand' },
    { id: 'NI-sky', name: 'Nicaragua' },
    { id: 'NE-sky', name: 'Niger' },
    { id: 'NG-sky', name: 'Nigeria' },
    { id: 'NU-sky', name: 'Niue Island' },
    { id: 'NF-sky', name: 'Norfolk Island' },
    { id: 'KP-sky', name: 'North Korea' },
    { id: 'MK-sky', name: 'North Macedonia' },
    { id: 'MP-sky', name: 'Northern Mariana Islands' },
    { id: 'NO-sky', name: 'Norway' },
    { id: 'OM-sky', name: 'Oman' },
    { id: 'PK-sky', name: 'Pakistan' },
    { id: 'PW-sky', name: 'Palau' },
    { id: 'PS-sky', name: 'Palestinian Territory' },
    { id: 'PA-sky', name: 'Panama' },
    { id: 'PG-sky', name: 'Papua New Guinea' },
    { id: 'PY-sky', name: 'Paraguay' },
    { id: 'PE-sky', name: 'Peru' },
    { id: 'PH-sky', name: 'Philippines' },
    { id: 'PN-sky', name: 'Pitcairn' },
    { id: 'PL-sky', name: 'Poland' },
    { id: 'PT-sky', name: 'Portugal' },
    { id: 'PR-sky', name: 'Puerto Rico' },
    { id: 'QA-sky', name: 'Qatar' },
    { id: 'CG-sky', name: 'Republic of the Congo' },
    { id: 'RE-sky', name: 'Reunion' },
    { id: 'RO-sky', name: 'Romania' },
    { id: 'RU-sky', name: 'Russia' },
    { id: 'RW-sky', name: 'Rwanda' },
    { id: 'GS-sky', name: 'S. Georgia and S. Sandwich Isls.' },
    { id: 'BL-sky', name: 'Saint Barthelemy' },
    { id: 'KN-sky', name: 'Saint Kitts and Nevis' },
    { id: 'LC-sky', name: 'Saint Lucia' },
    { id: 'VC-sky', name: 'Saint Vincent and the Grenadines' },
    { id: 'WS-sky', name: 'Samoa' },
    { id: 'SM-sky', name: 'San Marino' },
    { id: 'ST-sky', name: 'Sao Tome and Principe' },
    { id: 'SA-sky', name: 'Saudi Arabia' },
    { id: 'SN-sky', name: 'Senegal' },
    { id: 'RS-sky', name: 'Serbia' },
    { id: 'SC-sky', name: 'Seychelles' },
    { id: 'SL-sky', name: 'Sierra Leone' },
    { id: 'SG-sky', name: 'Singapore' },
    { id: 'SK-sky', name: 'Slovakia' },
    { id: 'SI-sky', name: 'Slovenia' },
    { id: 'SB-sky', name: 'Solomon Islands' },
    { id: 'SO-sky', name: 'Somalia' },
    { id: 'ZA-sky', name: 'South Africa' },
    { id: 'KR-sky', name: 'South Korea' },
    { id: 'SS-sky', name: 'South Sudan' },
    { id: 'ES-sky', name: 'Spain' },
    { id: 'LK-sky', name: 'Sri Lanka' },
    { id: 'SX-sky', name: 'St Maarten' },
    { id: 'SH-sky', name: 'St. Helena' },
    { id: 'PM-sky', name: 'St. Pierre and Miquelon' },
    { id: 'SD-sky', name: 'Sudan' },
    { id: 'SR-sky', name: 'Suriname' },
    { id: 'SJ-sky', name: 'Svalbard and Jan Mayen Islands' },
    { id: 'SE-sky', name: 'Sweden' },
    { id: 'CH-sky', name: 'Switzerland' },
    { id: 'SY-sky', name: 'Syria' },
    { id: 'TW-sky', name: 'Taiwan' },
    { id: 'TJ-sky', name: 'Tajikistan' },
    { id: 'TZ-sky', name: 'Tanzania' },
    { id: 'TH-sky', name: 'Thailand' },
    { id: 'TL-sky', name: 'Timor-Leste' },
    { id: 'TG-sky', name: 'Togo' },
    { id: 'TK-sky', name: 'Tokelau' },
    { id: 'TO-sky', name: 'Tonga' },
    { id: 'TT-sky', name: 'Trinidad and Tobago' },
    { id: 'TN-sky', name: 'Tunisia' },
    { id: 'TR-sky', name: 'Turkey' },
    { id: 'TM-sky', name: 'Turkmenistan' },
    { id: 'TC-sky', name: 'Turks and Caicos Islands' },
    { id: 'TV-sky', name: 'Tuvalu' },
    { id: 'UM-sky', name: 'US Minor Outlying Islands' },
    { id: 'VI-sky', name: 'US Virgin Islands' },
    { id: 'UG-sky', name: 'Uganda' },
    { id: 'UA-sky', name: 'Ukraine' },
    { id: 'AE-sky', name: 'United Arab Emirates' },
    { id: 'UK-sky', name: 'United Kingdom' },
    { id: 'US-sky', name: 'United States' },
    { id: 'UY-sky', name: 'Uruguay' },
    { id: 'UZ-sky', name: 'Uzbekistan' },
    { id: 'VU-sky', name: 'Vanuatu' },
    { id: 'VA-sky', name: 'Vatican City State (Holy See)' },
    { id: 'VE-sky', name: 'Venezuela' },
    { id: 'VN-sky', name: 'Vietnam' },
    { id: 'WF-sky', name: 'Wallis and Futuna Islands' },
    { id: 'EH-sky', name: 'Western Sahara' },
    { id: 'YE-sky', name: 'Yemen' },
    { id: 'ZM-sky', name: 'Zambia' },
    { id: 'ZW-sky', name: 'Zimbabwe' },
  ];

  const countiress = countries.map((el) => (
    <option key={el.id} value={el.id}>
      {el.name}
    </option>
  ));

  return countiress;
}
